"use client";

import {useEffect,useMemo,useState} from "react";

type Item={id:number;sku:string;sourceSku?:string|null;title:string;quantity:number;cogs:number|null;condition?:string|null;location?:string|null;workflowStatus?:string;dispositionStatus?:string;disposedAt?:string|null;dispositionNote?:string|null;purchaseStore?:string|null;purchaseDate?:string|null;listDate?:string|null;listPrice?:number|null;unlisted:boolean};
type Workflow="NEEDS_PHOTOS"|"PHOTOS_DONE"|"LISTED";
type Platform="EBAY"|"POSHMARK"|"MERCARI"|"DEPOP";

const today=()=>new Date().toISOString().slice(0,10);
const emptyItem={sku:"",sourceSku:"",title:"",quantity:1,cogs:"",condition:"Pre-owned",location:"",workflowStatus:"NEEDS_PHOTOS",dispositionStatus:"ACTIVE",purchaseStore:"",purchaseDate:today(),listDate:"",listPrice:"",unlisted:true};
const effectiveDisposition=(i:Item)=>{const d=i.dispositionStatus||"ACTIVE";if(d==="ACTIVE"&&i.quantity<=0)return "SOLD";if(d==="TRASHED")return "DISCARDED";return d};
const statusLabel=(i:Item)=>{const d=effectiveDisposition(i);if(d!=="ACTIVE")return d;return i.workflowStatus==="NEEDS_PHOTOS"?"NEEDS PHOTOS":i.workflowStatus==="PHOTOS_DONE"?"PHOTOS DONE":"LISTED"};

export default function InventoryPage(){
 const[items,setItems]=useState<Item[]>([]),[search,setSearch]=useState(""),[status,setStatus]=useState("ACTIVE"),[selected,setSelected]=useState<number[]>([]);
 const[showItem,setShowItem]=useState(false),[editingId,setEditingId]=useState<number|null>(null),[form,setForm]=useState<any>(emptyItem),[busy,setBusy]=useState(false);
 const[soldItem,setSoldItem]=useState<Item|null>(null),[soldForm,setSoldForm]=useState<any>({platform:"EBAY",saleAmount:"",soldAt:today(),quantity:1});
 async function load(){setItems(await fetch("/api/inventory").then(r=>r.json()))}
 useEffect(()=>{const q=new URLSearchParams(window.location.search).get("status");if(q)setStatus(q);load()},[]);
 const active=items.filter(i=>effectiveDisposition(i)==="ACTIVE");
 const counts={ACTIVE:active.length,NEEDS_PHOTOS:active.filter(i=>i.workflowStatus==="NEEDS_PHOTOS").length,PHOTOS_DONE:active.filter(i=>i.workflowStatus==="PHOTOS_DONE").length,LISTED:active.filter(i=>i.workflowStatus==="LISTED").length,SOLD:items.filter(i=>effectiveDisposition(i)==="SOLD").length,DONATED:items.filter(i=>effectiveDisposition(i)==="DONATED").length,DISCARDED:items.filter(i=>effectiveDisposition(i)==="DISCARDED").length};
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return items.filter(i=>{const d=effectiveDisposition(i);const matchStatus=status==="ALL"?true:status==="ACTIVE"?d==="ACTIVE":["NEEDS_PHOTOS","PHOTOS_DONE","LISTED"].includes(status)?d==="ACTIVE"&&i.workflowStatus===status:d===status;const text=[i.sku,i.sourceSku,i.title,i.purchaseStore,i.location].filter(Boolean).join(" ").toLowerCase();return matchStatus&&(!q||text.includes(q))})},[items,search,status]);
 const selectable=filtered.filter(i=>effectiveDisposition(i)==="ACTIVE").map(i=>i.id),allSelected=selectable.length>0&&selectable.every(id=>selected.includes(id));
 function edit(i:Item){setEditingId(i.id);setForm({sku:i.sku,sourceSku:i.sourceSku||"",title:i.title,quantity:i.quantity,cogs:i.cogs??"",condition:i.condition||"Pre-owned",location:i.location||"",workflowStatus:i.workflowStatus||"LISTED",dispositionStatus:i.dispositionStatus||"ACTIVE",purchaseStore:i.purchaseStore||"",purchaseDate:i.purchaseDate?.slice(0,10)||"",listDate:i.listDate?.slice(0,10)||"",listPrice:i.listPrice??"",unlisted:(i.workflowStatus||"LISTED")!=="LISTED"});setShowItem(true)}
 async function saveItem(e:React.FormEvent){e.preventDefault();setBusy(true);try{const payload={...form,quantity:Number(form.quantity),cogs:form.cogs===""?null:Number(form.cogs),listPrice:form.listPrice===""?null:Number(form.listPrice),unlisted:form.workflowStatus!=="LISTED"};const r=await fetch(editingId?`/api/inventory/${editingId}`:"/api/inventory",{method:editingId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok){alert(d.error||"Could not save item");return}setShowItem(false);setEditingId(null);setForm({...emptyItem});await load()}finally{setBusy(false)}}
 async function move(i:Item,workflowStatus:Workflow){const r=await fetch(`/api/inventory/${i.id}/workflow`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({workflowStatus})});if(!r.ok){alert((await r.json()).error||"Could not update item");return}await load()}
 async function bulkMove(workflowStatus:Workflow){if(!selected.length)return;setBusy(true);try{const r=await fetch("/api/inventory/workflow/bulk",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids:selected,workflowStatus})});if(!r.ok){alert((await r.json()).error||"Could not update items");return}setSelected([]);await load()}finally{setBusy(false)}}
 async function dispose(i:Item,dispositionStatus:"DONATED"|"DISCARDED"){if(!confirm(`Mark ${i.title} as ${dispositionStatus.toLowerCase()}?`))return;const r=await fetch(`/api/inventory/${i.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...i,sourceSku:i.sourceSku||"",workflowStatus:i.workflowStatus||"LISTED",dispositionStatus,disposedAt:today()})});if(!r.ok){alert((await r.json()).error||"Could not update item");return}await load()}
 async function restore(i:Item){const quantity=Math.max(1,i.quantity||1);const r=await fetch(`/api/inventory/${i.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...i,quantity,sourceSku:i.sourceSku||"",workflowStatus:i.workflowStatus||"LISTED",dispositionStatus:"ACTIVE",disposedAt:null,dispositionNote:null})});if(!r.ok){alert((await r.json()).error||"Could not restore item");return}await load()}
 function openSold(i:Item){setSoldItem(i);setSoldForm({platform:"EBAY",saleAmount:"",soldAt:today(),quantity:1})}
 async function saveSold(e:React.FormEvent){e.preventDefault();if(!soldItem)return;setBusy(true);try{const r=await fetch(`/api/inventory/${soldItem.id}/sold`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...soldForm,saleAmount:Number(soldForm.saleAmount),quantity:Number(soldForm.quantity)})});const d=await r.json();if(!r.ok){alert(d.error||"Could not mark sold");return}setSoldItem(null);await load()}finally{setBusy(false)}}
 return <main className="shell">
  <nav className="globalNav"><a href="/">Dashboard</a><a href="/inventory">Inventory</a><a href="/listings">Listed</a><a href="/sales">Sold</a></nav>
  <header className="header"><div><a className="back" href="/">← Dashboard</a><h1>Inventory</h1><p>Track what came in, what needs photos, what is listed, and how each item leaves inventory.</p></div><div className="actions"><a className="button secondary" href="/inventory/bulk-entry">Quick Add</a><button onClick={()=>{setEditingId(null);setForm({...emptyItem});setShowItem(true)}}>+ Inventory</button></div></header>
  <section className="cards">{[["Active","ACTIVE"],["Needs Photos","NEEDS_PHOTOS"],["Photos Done","PHOTOS_DONE"],["Listed","LISTED"],["Sold","SOLD"],["Donated","DONATED"],["Discarded","DISCARDED"]].map(([label,key])=><button className="card" key={key} onClick={()=>setStatus(key)}><span>{label}</span><strong>{(counts as any)[key]}</strong></button>)}</section>
  <section className="panel"><div className="toolbar"><div><h2>Items</h2><span>{filtered.length} shown{selected.length?` · ${selected.length} selected`:""}</span></div><div className="actions"><select value={status} onChange={e=>{setStatus(e.target.value);setSelected([])}}>{["ACTIVE","NEEDS_PHOTOS","PHOTOS_DONE","LISTED","SOLD","DONATED","DISCARDED","ALL"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search SKU, item, store, location..."/></div></div>
   {selected.length>0&&<div className="toolbar"><b>{selected.length} selected</b><div className="actions"><button className="secondary" disabled={busy} onClick={()=>bulkMove("NEEDS_PHOTOS")}>Needs Photos</button><button className="secondary" disabled={busy} onClick={()=>bulkMove("PHOTOS_DONE")}>Photos Done</button><button disabled={busy} onClick={()=>bulkMove("LISTED")}>Listed</button><button className="secondary" onClick={()=>setSelected([])}>Clear</button></div></div>}
   <table><thead><tr><th><input type="checkbox" checked={allSelected} onChange={()=>setSelected(allSelected?[]:[...new Set([...selected,...selectable])])}/></th><th>RH SKU</th><th>Item</th><th>COGS</th><th>Store / Date</th><th>Location</th><th>Qty</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(i=>{const d=effectiveDisposition(i);return <tr key={i.id}><td>{d==="ACTIVE"&&<input type="checkbox" checked={selected.includes(i.id)} onChange={()=>setSelected(s=>s.includes(i.id)?s.filter(x=>x!==i.id):[...s,i.id])}/>}</td><td><b>{i.sku}</b>{i.sourceSku&&<small>{i.sourceSku}</small>}</td><td>{i.title}</td><td>{i.cogs==null?"—":`$${i.cogs.toFixed(2)}`}</td><td>{i.purchaseStore||"—"}<small>{i.purchaseDate?new Date(i.purchaseDate).toLocaleDateString():""}</small></td><td>{i.location||"—"}</td><td>{i.quantity}</td><td><span className={"badge "+(statusLabel(i)==="LISTED"||statusLabel(i)==="SOLD"?"matched":"new")}>{statusLabel(i)}</span>{i.disposedAt&&d!=="ACTIVE"&&<small>{new Date(i.disposedAt).toLocaleDateString()}</small>}</td><td className="rowActions"><button className="linkBtn" onClick={()=>edit(i)}>Edit</button>{d==="ACTIVE"?<><button className="linkBtn" onClick={()=>move(i,"NEEDS_PHOTOS")}>Needs Photos</button><button className="linkBtn" onClick={()=>move(i,"PHOTOS_DONE")}>Photos Done</button><button className="linkBtn" onClick={()=>move(i,"LISTED")}>Listed</button><button className="linkBtn" onClick={()=>openSold(i)}>Sold</button><button className="linkBtn" onClick={()=>dispose(i,"DONATED")}>Donate</button><button className="linkBtn danger" onClick={()=>dispose(i,"DISCARDED")}>Discard</button></>:d!=="SOLD"&&<button className="linkBtn" onClick={()=>restore(i)}>Restore</button>}</td></tr>})}</tbody></table>
  </section>
  {showItem&&<div className="modalWrap" onMouseDown={e=>{if(e.target===e.currentTarget)setShowItem(false)}}><form className="modal" onSubmit={saveItem}><div className="modalHead"><h2>{editingId?"Edit Inventory":"Add Inventory"}</h2><button type="button" className="x" onClick={()=>setShowItem(false)}>×</button></div><div className="two"><label>RH SKU<input required value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></label><label>Source SKU <small>(optional)</small><input value={form.sourceSku} onChange={e=>setForm({...form,sourceSku:e.target.value})}/></label></div><label>Item title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="two"><label>Quantity<input type="number" min="0" required value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>COGS per item<input type="number" min="0" step="0.01" value={form.cogs} onChange={e=>setForm({...form,cogs:e.target.value})}/></label></div><div className="two"><label>Purchase store<input value={form.purchaseStore} onChange={e=>setForm({...form,purchaseStore:e.target.value})}/></label><label>Purchase date<input type="date" value={form.purchaseDate} onChange={e=>setForm({...form,purchaseDate:e.target.value})}/></label></div><div className="two"><label>Condition<input value={form.condition} onChange={e=>setForm({...form,condition:e.target.value})}/></label><label>Storage location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label></div><div className="two"><label>Workflow<select value={form.workflowStatus} onChange={e=>setForm({...form,workflowStatus:e.target.value})}><option value="NEEDS_PHOTOS">Needs Photos</option><option value="PHOTOS_DONE">Photos Done</option><option value="LISTED">Listed</option></select></label><label>List date<input type="date" value={form.listDate} onChange={e=>setForm({...form,listDate:e.target.value})}/></label></div><label>List price <small>(optional)</small><input type="number" min="0" step="0.01" value={form.listPrice} onChange={e=>setForm({...form,listPrice:e.target.value})}/></label><div className="modalActions"><button type="button" className="secondary" onClick={()=>setShowItem(false)}>Cancel</button><button disabled={busy}>Save Item</button></div></form></div>}
  {soldItem&&<div className="modalWrap" onMouseDown={e=>{if(e.target===e.currentTarget)setSoldItem(null)}}><form className="modal" onSubmit={saveSold}><div className="modalHead"><h2>Mark Sold</h2><button type="button" className="x" onClick={()=>setSoldItem(null)}>×</button></div><div className="hint"><b>{soldItem.sku}</b> · {soldItem.title}</div><div className="two"><label>Marketplace<select value={soldForm.platform} onChange={e=>setSoldForm({...soldForm,platform:e.target.value})}>{(["EBAY","POSHMARK","MERCARI","DEPOP"] as Platform[]).map(p=><option key={p}>{p}</option>)}</select></label><label>Sold date<input type="date" required value={soldForm.soldAt} onChange={e=>setSoldForm({...soldForm,soldAt:e.target.value})}/></label></div><div className="two"><label>Sold price<input type="number" min="0" step="0.01" required value={soldForm.saleAmount} onChange={e=>setSoldForm({...soldForm,saleAmount:e.target.value})}/></label><label>Quantity<input type="number" min="1" max={soldItem.quantity} value={soldForm.quantity} onChange={e=>setSoldForm({...soldForm,quantity:e.target.value})}/></label></div><div className="modalActions"><button type="button" className="secondary" onClick={()=>setSoldItem(null)}>Cancel</button><button disabled={busy}>Mark Sold</button></div></form></div>}
 </main>
}
