"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";

type BulkBuy={id:number;name:string;purchasedQty:number;totalCost:number};
type Existing={sku:string;sourceSku?:string|null;title:string;cogs?:number|null;purchaseDate?:string|null};
type Row={sku:string;sourceSku:string;title:string;quantity:number;cogs:string;condition:string;location:string;bulkBuyId:string;workflowStatus:string;purchaseStore:string;purchaseDate:string;listDate:string;listPrice:string;createdAt:string;duplicate?:boolean;duplicateReason?:string};
const blank=():Row=>({sku:"",sourceSku:"",title:"",quantity:1,cogs:"",condition:"Good",location:"",bulkBuyId:"",workflowStatus:"NEEDS_PHOTOS",purchaseStore:"",purchaseDate:"",listDate:"",listPrice:"",createdAt:""});
function makeSku(prefix:string,n:number){const p=prefix.trim().toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,5)||"RH";return `${p}-${String(n).padStart(6,"0")}`}
function parseCsv(text:string){const records:string[][]=[];let row:string[]=[],field="",quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted}else if(ch===','&&!quoted){row.push(field);field=""}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(field);field="";if(row.some(v=>v.trim()))records.push(row);row=[]}else field+=ch}row.push(field);if(row.some(v=>v.trim()))records.push(row);return records}
function normalizeHeader(v:string){return v.toLowerCase().replace(/[^a-z0-9]/g,"")}
function norm(v:string){return String(v||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function pick(record:string[],headers:string[],names:string[]){for(const name of names){const at=headers.indexOf(name);if(at>=0)return(record[at]??"").trim()}return""}
function workflow(v:string){const n=v.toLowerCase().replace(/[^a-z]/g,"");if(n.includes("listed")&&!n.includes("unlisted"))return"LISTED";if(n.includes("photo")&&(n.includes("done")||n.includes("taken")||n.includes("ready")))return"PHOTOS_DONE";return"NEEDS_PHOTOS"}
function cellText(v:any){if(v==null)return"";if(v instanceof Date)return v.toISOString().slice(0,10);if(typeof v==="object"){if("text" in v)return String(v.text??"");if("result" in v)return String(v.result??"");if(Array.isArray(v.richText))return v.richText.map((x:any)=>x.text||"").join("")}return String(v)}
function rowColorStatus(row:any){const cells:any[]=[];row.eachCell({includeEmpty:true},(c:any)=>cells.push(c));for(const c of cells){const fill:any=c.fill;if(!fill||fill.type!=="pattern")continue;const argb=fill.fgColor?.argb||fill.bgColor?.argb;if(!argb||argb.length<6)continue;const rgb=argb.slice(-6),r=parseInt(rgb.slice(0,2),16),g=parseInt(rgb.slice(2,4),16),b=parseInt(rgb.slice(4,6),16);if(Number.isNaN(r+g+b))continue;if(r>150&&g>120&&b<160)return"PHOTOS_DONE";if(g>100&&g>r*1.12&&g>b*1.12)return"LISTED"}return"NEEDS_PHOTOS"}
function nextRh(existing:Existing[]){let max=0;for(const x of existing){const m=/^RH-(\d+)$/i.exec(x.sku||"");if(m)max=Math.max(max,Number(m[1]))}return max+1}
function markDuplicates(rows:Row[],existing:Existing[]){const byTitle=new Map<string,Existing[]>();for(const x of existing){const k=norm(x.title);if(!k)continue;const a=byTitle.get(k)||[];a.push(x);byTitle.set(k,a)}return rows.map(r=>{const exact=byTitle.get(norm(r.title))||[];const source=r.sourceSku.trim();let hit=exact.find(x=>source&&x.sourceSku?.trim()===source);if(!hit&&exact.length===1)hit=exact[0];if(!hit)return r;return{...r,duplicate:true,duplicateReason:`Possible existing item: ${hit.sku}${hit.sourceSku?` / ${hit.sourceSku}`:""}`}})}

export default function BulkEntryPage(){
 const[bulkBuys,setBulkBuys]=useState<BulkBuy[]>([]),[existing,setExisting]=useState<Existing[]>([]),[rows,setRows]=useState<Row[]>([blank(),blank(),blank()]);const[prefix,setPrefix]=useState("RH"),[nextNumber,setNextNumber]=useState(1),[selectedBulk,setSelectedBulk]=useState(""),[batchStore,setBatchStore]=useState(""),[batchDate,setBatchDate]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{Promise.all([fetch("/api/bulk-buys").then(r=>r.json()),fetch("/api/inventory").then(r=>r.json())]).then(([buys,inv])=>{setBulkBuys(Array.isArray(buys)?buys:[]);const list=Array.isArray(inv)?inv:[];setExisting(list);setNextNumber(nextRh(list))}).catch(()=>{})},[]);
 function update(i:number,key:keyof Row,value:any){setRows(r=>r.map((x,n)=>n===i?{...x,[key]:value,duplicate:false,duplicateReason:""}:x))}function generateSkus(){let used=0;setRows(r=>r.map(x=>x.sku?x:{...x,sku:makeSku(prefix,nextNumber+used++)}));setNextNumber(n=>n+used)}function addRows(count=5){setRows(r=>[...r,...Array.from({length:count},()=>({...blank(),purchaseStore:batchStore,purchaseDate:batchDate}))])}
 function fromRecord(record:string[],headers:string[],n:number,statusOverride?:string){const title=pick(record,headers,["title","itemtitle","itemname","name","listingtitle","description","itemdescription","item"]);if(!title||title.toLowerCase()==="total")return null;const qty=Number(pick(record,headers,["quantity","qty","availablequantity"]))||1;const sourceSku=pick(record,headers,["sku","sourcesku","customlabel","customlabelsku","inventorysku"]);const status=pick(record,headers,["workflowstatus","status","listingstatus"]);return{sku:makeSku("RH",n),sourceSku,title,quantity:Math.max(1,qty),cogs:pick(record,headers,["cogs","cost","costofgoods","itemcost","purchaseprice","purchasecost"]),condition:pick(record,headers,["condition","condtion"])||"Good",location:pick(record,headers,["location","bin","storagelocation","newlocation"]),bulkBuyId:selectedBulk,workflowStatus:status?workflow(status):(statusOverride||"NEEDS_PHOTOS"),purchaseStore:pick(record,headers,["purchasestore","store","sourcedat","source","purchase"]),purchaseDate:pick(record,headers,["purchasedate","datepurchased","dateofpurchase","sourcedate"]),listDate:pick(record,headers,["listdate","listingdate","datelisted"]),listPrice:pick(record,headers,["listprice","listingprice","price"]),createdAt:pick(record,headers,["importedcreatedat","createdat","datecreated"])} satisfies Row}
 async function importFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setMessage("");try{let imported:Row[]=[];const start=nextRh(existing);
   if(file.name.toLowerCase().endsWith(".xlsx")){const ExcelJS=(await import("exceljs")).default;const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());const ws=wb.worksheets.find((s:any)=>String(s.name).trim()==="2026")||wb.worksheets[0];if(!ws){setMessage("That workbook has no worksheet.");return}const headerRow=ws.getRow(1);const headers:string[]=[];for(let c=1;c<=headerRow.cellCount;c++)headers.push(normalizeHeader(cellText(headerRow.getCell(c).value)));let n=start;ws.eachRow((row:any,rowNumber:number)=>{if(rowNumber===1)return;const record:string[]=[];for(let c=1;c<=headers.length;c++)record.push(cellText(row.getCell(c).value).trim());const item=fromRecord(record,headers,n,rowColorStatus(row));if(item){imported.push(item);n++}})
   }else{const records=parseCsv(await file.text());if(records.length<2){setMessage("CSV needs a header row and at least one item.");return}const headers=records[0].map(normalizeHeader);let n=start;imported=records.slice(1).map(record=>{const item=fromRecord(record,headers,n,"LISTED");if(item)n++;return item}).filter(Boolean) as Row[]}
   if(!imported.length){setMessage("No inventory rows were found.");return}imported=markDuplicates(imported,existing);setRows(imported);setNextNumber(start+imported.length);const counts=imported.reduce((a,r)=>{a[r.workflowStatus]=(a[r.workflowStatus]||0)+1;return a},{} as Record<string,number>),dupes=imported.filter(r=>r.duplicate).length;setMessage(`${imported.length} rows loaded — ${counts.NEEDS_PHOTOS||0} Needs Photos, ${counts.PHOTOS_DONE||0} Photos Done, ${counts.LISTED||0} Listed.${dupes?` ${dupes} possible duplicates flagged and excluded from Save All.`:""} Review before saving.`)
  }catch(err){console.error(err);setMessage("I couldn't read that file. Please use a standard .xlsx or .csv file.")}finally{e.target.value=""}}
 async function saveAll(){const valid=rows.filter(r=>r.title.trim()&&!r.duplicate);if(!valid.length){setMessage("There are no new inventory rows ready to save.");return}setBusy(true);setMessage("");let used=0;const items=valid.map(row=>({...row,sku:row.sku.trim()||makeSku("RH",nextNumber+used++),quantity:Number(row.quantity),cogs:row.cogs===""?null:Number(row.cogs),listPrice:row.listPrice===""?null:Number(row.listPrice),bulkBuyId:null,unlisted:row.workflowStatus!=="LISTED"}));const res=await fetch("/api/inventory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items})});const data=await res.json().catch(()=>({}));if(!res.ok){setMessage(data.error||"Inventory import failed.");setBusy(false);return}setNextNumber(n=>n+used);setRows([{...blank(),purchaseStore:batchStore,purchaseDate:batchDate},{...blank(),purchaseStore:batchStore,purchaseDate:batchDate},{...blank(),purchaseStore:batchStore,purchaseDate:batchDate}]);setExisting(old=>[...old,...items.map(x=>({sku:x.sku,sourceSku:x.sourceSku,title:x.title,cogs:x.cogs,purchaseDate:x.purchaseDate}))]);setMessage(`${data.created} new inventory items imported successfully. Possible duplicates were not imported.`);setBusy(false)}
 const selected=useMemo(()=>bulkBuys.find(b=>String(b.id)===selectedBulk),[bulkBuys,selectedBulk]);return <main className="shell"><header className="header"><div><a className="back" href="/inventory">← Inventory</a><h1>Quick Add Inventory</h1><p>Add sourcing inventory now; RH SKU is internal and Source SKU may be blank.</p></div><div className="actions"><label className="secondary" style={{cursor:"pointer"}}>Import Excel / CSV<input type="file" accept=".xlsx,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv" onChange={importFile} style={{display:"none"}}/></label><button className="secondary" onClick={generateSkus}>Generate Missing RH SKUs</button><button onClick={saveAll} disabled={busy}>{busy?"Saving...":"Save All New Items"}</button></div></header>
 <section className="panel"><div className="toolbar"><div><h2>Batch Settings</h2><span>Set Store and Purchase Date once and they will apply to every row in this batch.</span></div></div><div className="batchSettings"><label>Store for this batch<input value={batchStore} placeholder="e.g. Goodwill Des Plaines" onChange={e=>{const value=e.target.value;setBatchStore(value);setRows(rs=>rs.map(r=>({...r,purchaseStore:value})))}}/></label><label>Purchase date for this batch<input type="date" value={batchDate} onChange={e=>{const value=e.target.value;setBatchDate(value);setRows(rs=>rs.map(r=>({...r,purchaseDate:value})))}}/></label><label>RH SKU prefix<input value={prefix} onChange={e=>setPrefix(e.target.value)}/></label><label>Next RH number<input type="number" min="1" value={nextNumber} onChange={e=>setNextNumber(Number(e.target.value))}/></label><label>Bulk purchase<select value={selectedBulk} onChange={e=>{setSelectedBulk(e.target.value);setRows(rs=>rs.map(r=>({...r,bulkBuyId:e.target.value})))}}><option value="">None</option>{bulkBuys.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div>{selected&&<div className="hint">Selected buy: <b>{selected.name}</b> — ${selected.totalCost.toFixed(2)} / {selected.purchasedQty} units.</div>}{message&&<div className="successMessage">{message}</div>}</section>
 <section className="panel"><div className="panelHead"><h2>Items</h2><span>{rows.length} rows</span></div><div className="bulkTableWrap"><table className="bulkTable"><thead><tr><th>#</th><th>RH SKU</th><th>Source SKU</th><th>Title *</th><th>Qty *</th><th>COGS / Unit</th><th>Condition</th><th>Store</th><th>Purchase Date</th><th>Workflow</th><th>Check</th><th></th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{i+1}</td><td><input value={r.sku} onChange={e=>update(i,"sku",e.target.value)} placeholder="auto"/></td><td><input value={r.sourceSku} onChange={e=>update(i,"sourceSku",e.target.value)} placeholder="optional"/></td><td className="wide"><input value={r.title} onChange={e=>update(i,"title",e.target.value)}/></td><td><input className="smallInput" type="number" min="1" step="1" value={r.quantity} onChange={e=>update(i,"quantity",Math.max(1,Number(e.target.value)||1))}/></td><td><input className="smallInput" type="number" min="0" step="0.01" value={r.cogs} onChange={e=>update(i,"cogs",e.target.value)}/></td><td><select value={r.condition} onChange={e=>update(i,"condition",e.target.value)}><option value="New">New</option><option value="Excellent">Excellent</option><option value="Good">Good</option><option value="Fair">Fair</option></select></td><td><input value={r.purchaseStore} onChange={e=>update(i,"purchaseStore",e.target.value)}/></td><td><input type="date" value={r.purchaseDate} onChange={e=>update(i,"purchaseDate",e.target.value)}/></td><td><select value={r.workflowStatus} onChange={e=>update(i,"workflowStatus",e.target.value)}><option value="NEEDS_PHOTOS">Needs Photos</option><option value="PHOTOS_DONE">Photos Done</option><option value="LISTED">Listed</option></select></td><td>{r.duplicate?<span title={r.duplicateReason}>⚠ Possible duplicate</span>:"New"}</td><td><button className="linkBtn danger" onClick={()=>setRows(rs=>rs.filter((_,n)=>n!==i))}>×</button></td></tr>)}</tbody></table></div><div className="tableFooter"><button className="secondary" onClick={()=>addRows(5)}>+ Add 5 Rows</button><button className="secondary" onClick={()=>addRows(10)}>+ Add 10 Rows</button></div></section></main>}
