"use client";
import {useEffect,useMemo,useState} from "react";

type Item={id:number;sku:string;title:string;quantity:number;cogs:number|null;location:string|null};
type Line={id:number;title:string;quantity:number;unitPrice:number;inventoryItemId:number|null;inventoryItem?:Item|null};
type Sale={id:number;platform:string;externalOrderId:string|null;buyerUsername:string|null;saleAmount:number;fees:number;shippingCost:number;status:string;soldAt:string;lines:Line[]};

function money(n:number){return `$${n.toFixed(2)}`}
export default function SalesPage(){
 const [sales,setSales]=useState<Sale[]>([]),[items,setItems]=useState<Item[]>([]),[search,setSearch]=useState(""),[filter,setFilter]=useState("ALL"),[show,setShow]=useState(false),[matchSale,setMatchSale]=useState<Sale|null>(null),[matchId,setMatchId]=useState(""),[form,setForm]=useState<any>({platform:"EBAY",externalOrderId:"",externalListingId:"",buyerUsername:"",title:"",quantity:1,saleAmount:"",fees:"",shippingCost:""}),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function load(){const [s,i]=await Promise.all([fetch('/api/sales').then(r=>r.json()),fetch('/api/inventory').then(r=>r.json())]);setSales(s);setItems(i)} useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>sales.filter(s=>{const q=search.toLowerCase();const text=[s.externalOrderId,s.buyerUsername,...s.lines.map(l=>l.title),s.lines[0]?.inventoryItem?.sku].filter(Boolean).join(' ').toLowerCase();return (!q||text.includes(q))&&(filter==='ALL'||s.status===filter)}),[sales,search,filter]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');try{const r=await fetch('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,saleAmount:Number(form.saleAmount),fees:Number(form.fees||0),shippingCost:Number(form.shippingCost||0),quantity:Number(form.quantity)})});const d=await r.json();if(!r.ok){setMsg(d.error||'Could not create sale');return}setShow(false);setForm({platform:'EBAY',externalOrderId:'',externalListingId:'',buyerUsername:'',title:'',quantity:1,saleAmount:'',fees:'',shippingCost:''});await load()}finally{setBusy(false)}}
 async function match(){if(!matchSale||!matchId)return;setBusy(true);setMsg('');try{const r=await fetch(`/api/sales/${matchSale.id}/match`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({inventoryItemId:Number(matchId)})});const d=await r.json();if(!r.ok){setMsg(d.error||'Could not match sale');return}setMatchSale(null);setMatchId('');await load()}finally{setBusy(false)}}
 const unmatched=filtered.filter(s=>s.status==='NEW').length;
 return <main className="shell"><header className="header"><div><a className="back" href="/">← Dashboard</a><h1>Sales</h1><p>Sales become inventory events and feed the pick/pack workflow.</p></div><button onClick={()=>setShow(true)}>+ Record Sale</button></header>
 <section className="cards"><div className="card"><span>Total Sales</span><strong>{sales.length}</strong></div><div className="card"><span>Needs Match</span><strong>{sales.filter(s=>s.status==='NEW').length}</strong></div><div className="card"><span>Matched</span><strong>{sales.filter(s=>s.status==='MATCHED').length}</strong></div><div className="card"><span>Revenue</span><strong>{money(sales.reduce((n,s)=>n+s.saleAmount,0))}</strong></div></section>
 <section className="panel"><div className="toolbar"><div><h2>Sales Queue</h2><span>{unmatched?`${unmatched} sale(s) need matching`:'All current sales are matched'}</span></div><div className="filters"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All statuses</option><option value="NEW">Needs match</option><option value="MATCHED">Matched</option></select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search buyer, order, SKU..."/></div></div>
 <table><thead><tr><th>Sale</th><th>Buyer</th><th>Item / SKU</th><th>Amount</th><th>Fees</th><th>Profit*</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(s=>{const l=s.lines[0],c=l?.inventoryItem?.cogs??0,profit=s.saleAmount-s.fees-s.shippingCost-c*(l?.quantity??1);return <tr key={s.id}><td><b>{s.platform}</b><small>{s.externalOrderId||`Sale #${s.id}`}<br/>{new Date(s.soldAt).toLocaleString()}</small></td><td>{s.buyerUsername||'—'}</td><td>{l?.title}<small>{l?.inventoryItem?<><b>{l.inventoryItem.sku}</b> · {l.inventoryItem.location||'No location'}</>:'No SKU assigned'}</small></td><td>{money(s.saleAmount)}</td><td>{money(s.fees)}</td><td>{money(profit)}</td><td><span className={'badge '+(s.status==='MATCHED'?'matched':'new')}>{s.status}</span></td><td>{s.status==='NEW'&&<button className="linkBtn" onClick={()=>{setMatchSale(s);setMatchId('');setMsg('')}}>Match SKU</button>}</td></tr>})}</tbody></table><p className="footnote">* Profit is an MVP estimate: sale amount − marketplace fees − shipping cost − COGS.</p></section>
 {show&&<div className="modalWrap" onMouseDown={e=>{if(e.target===e.currentTarget)setShow(false)}}><form className="modal" onSubmit={save}><div className="modalHead"><h2>Record Sale</h2><button type="button" className="x" onClick={()=>setShow(false)}>×</button></div><div className="two"><label>Marketplace<select value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}>{['EBAY','POSHMARK','MERCARI','DEPOP'].map(x=><option key={x}>{x}</option>)}</select></label><label>Order ID<input value={form.externalOrderId} onChange={e=>setForm({...form,externalOrderId:e.target.value})}/></label></div><label>Listing ID (optional)<input value={form.externalListingId} onChange={e=>setForm({...form,externalListingId:e.target.value})} placeholder="Used for automatic SKU matching"/></label><label>Item title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="two"><label>Quantity<input type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Sale amount<input type="number" min="0" step="0.01" required value={form.saleAmount} onChange={e=>setForm({...form,saleAmount:e.target.value})}/></label></div><div className="two"><label>Fees<input type="number" min="0" step="0.01" value={form.fees} onChange={e=>setForm({...form,fees:e.target.value})}/></label><label>Shipping cost<input type="number" min="0" step="0.01" value={form.shippingCost} onChange={e=>setForm({...form,shippingCost:e.target.value})}/></label></div><label>Buyer username<input value={form.buyerUsername} onChange={e=>setForm({...form,buyerUsername:e.target.value})}/></label>{msg&&<div className="errorMessage">{msg}</div>}<div className="modalActions"><button type="button" className="secondary" onClick={()=>setShow(false)}>Cancel</button><button disabled={busy}>Record Sale</button></div></form></div>}
 {matchSale&&<div className="modalWrap" onMouseDown={e=>{if(e.target===e.currentTarget)setMatchSale(null)}}><form className="modal" onSubmit={e=>{e.preventDefault();match()}}><div className="modalHead"><h2>Match Sale to SKU</h2><button type="button" className="x" onClick={()=>setMatchSale(null)}>×</button></div><div className="hint"><b>{matchSale.platform}</b> · {matchSale.lines[0]?.title}<br/>Buyer: {matchSale.buyerUsername||'—'} · {money(matchSale.saleAmount)}</div><label>Inventory SKU<select required value={matchId} onChange={e=>setMatchId(e.target.value)}><option value="">Select SKU...</option>{items.map(i=><option key={i.id} value={i.id}>{i.sku} — {i.title} ({i.quantity} available)</option>)}</select></label>{msg&&<div className="errorMessage">{msg}</div>}<div className="modalActions"><button type="button" className="secondary" onClick={()=>setMatchSale(null)}>Cancel</button><button disabled={busy}>Match & Reduce Inventory</button></div></form></div>}
 </main>
}
