"use client";
import {useEffect,useMemo,useState} from "react";

type Item={id:number;sku:string;title:string;quantity:number;location:string|null;dispositionStatus?:string};
type Line={id:number;title:string;quantity:number;unitPrice:number;inventoryItemId:number|null;inventoryItem?:Item|null};
type Sale={id:number;platform:string;externalOrderId:string|null;buyerUsername:string|null;saleAmount:number;status:string;soldAt:string;lines:Line[]};
const money=(n:number)=>`$${n.toFixed(2)}`;

export default function SalesPage(){
 const[sales,setSales]=useState<Sale[]>([]),[items,setItems]=useState<Item[]>([]),[search,setSearch]=useState(""),[filter,setFilter]=useState("ALL"),[matchSale,setMatchSale]=useState<Sale|null>(null),[matchId,setMatchId]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function load(){const[s,i]=await Promise.all([fetch("/api/sales").then(r=>r.json()),fetch("/api/inventory").then(r=>r.json())]);setSales(s);setItems(i)}
 useEffect(()=>{const q=new URLSearchParams(window.location.search).get("status");if(q)setFilter(q);load()},[]);
 const filtered=useMemo(()=>sales.filter(s=>{const q=search.toLowerCase().trim();const text=[s.platform,s.externalOrderId,s.buyerUsername,...s.lines.map(l=>l.title),...s.lines.map(l=>l.inventoryItem?.sku)].filter(Boolean).join(" ").toLowerCase();const matched=filter==="ALL"?true:filter==="NEW"?s.status==="NEW":s.status!=="NEW"&&s.status!=="CANCELLED";return matched&&(!q||text.includes(q))}),[sales,search,filter]);
 const recorded=sales.filter(s=>s.status!=="NEW"&&s.status!=="CANCELLED"),needsMatch=sales.filter(s=>s.status==="NEW");
 async function match(){if(!matchSale||!matchId)return;setBusy(true);setMsg("");try{const r=await fetch(`/api/sales/${matchSale.id}/match`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({inventoryItemId:Number(matchId)})});const d=await r.json();if(!r.ok){setMsg(d.error||"Could not match sale");return}setMatchSale(null);setMatchId("");await load()}finally{setBusy(false)}}
 return <main className="shell">
  <nav className="globalNav"><a href="/">Dashboard</a><a href="/inventory">Inventory</a><a href="/listings">Listed</a><a href="/sales">Sold</a></nav>
  <header className="header"><div><a className="back" href="/">← Dashboard</a><h1>Sold</h1><p>Sold price, sold date and marketplace. COGS stays with the original inventory record.</p></div><a className="button" href="/inventory?status=LISTED">Mark an Item Sold</a></header>
  <section className="cards"><button className="card" onClick={()=>setFilter("SOLD")}><span>Recorded Sales</span><strong>{recorded.length}</strong></button><button className="card" onClick={()=>setFilter("NEW")}><span>Needs Match</span><strong>{needsMatch.length}</strong></button><div className="card"><span>Sold Revenue</span><strong>{money(recorded.reduce((n,s)=>n+s.saleAmount,0))}</strong></div><div className="card"><span>Marketplaces</span><strong>{new Set(recorded.map(s=>s.platform)).size}</strong></div></section>
  <section className="panel"><div className="toolbar"><div><h2>Sold History</h2><span>{filter==="NEW"?"Choose the correct inventory item for uncertain marketplace sales.":"A simple history of what sold."}</span></div><div className="actions"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All</option><option value="SOLD">Recorded Sales</option><option value="NEW">Needs Match</option></select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search item, SKU, buyer, order..."/></div></div>
   <table><thead><tr><th>Sold Date</th><th>Marketplace</th><th>Item</th><th>RH SKU</th><th>Qty</th><th>Sold Price</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(s=>{const l=s.lines[0];return <tr key={s.id}><td>{new Date(s.soldAt).toLocaleDateString()}</td><td><b>{s.platform}</b>{s.externalOrderId&&<small>{s.externalOrderId}</small>}</td><td>{l?.title||"—"}{s.buyerUsername&&<small>@{s.buyerUsername.replace(/^@/,"")}</small>}</td><td>{l?.inventoryItem?.sku||"—"}{l?.inventoryItem?.location&&<small>{l.inventoryItem.location}</small>}</td><td>{l?.quantity||1}</td><td><b>{money(s.saleAmount)}</b></td><td><span className={"badge "+(s.status==="NEW"?"new":"matched")}>{s.status==="NEW"?"NEEDS MATCH":"SOLD"}</span></td><td>{s.status==="NEW"&&<button className="linkBtn" onClick={()=>{setMatchSale(s);setMatchId("");setMsg("")}}>Match Item</button>}</td></tr>})}</tbody></table>
  </section>
  {matchSale&&<div className="modalWrap" onMouseDown={e=>{if(e.target===e.currentTarget)setMatchSale(null)}}><form className="modal" onSubmit={e=>{e.preventDefault();match()}}><div className="modalHead"><h2>Match Sold Item</h2><button type="button" className="x" onClick={()=>setMatchSale(null)}>×</button></div><div className="hint"><b>{matchSale.platform}</b> · {matchSale.lines[0]?.title}<br/>{new Date(matchSale.soldAt).toLocaleDateString()} · {money(matchSale.saleAmount)}</div><label>Inventory item<select required value={matchId} onChange={e=>setMatchId(e.target.value)}><option value="">Select RH SKU...</option>{items.filter(i=>(i.dispositionStatus||"ACTIVE")==="ACTIVE"&&i.quantity>0).map(i=><option key={i.id} value={i.id}>{i.sku} — {i.title} ({i.quantity} available)</option>)}</select></label>{msg&&<div className="errorMessage">{msg}</div>}<div className="modalActions"><button type="button" className="secondary" onClick={()=>setMatchSale(null)}>Cancel</button><button disabled={busy}>Match & Mark Sold</button></div></form></div>}
 </main>
}
