"use client";
import {useEffect,useMemo,useState} from "react";

type Item={cogs:number|null};
type Line={quantity:number;cogsAtSale?:number|null;inventoryItem?:Item|null};
type Sale={id:number;platform:string;saleAmount:number;fees:number;shippingCost:number;soldAt:string;status:string;lines:Line[]};
const BUYER_PAID_SHIPPING=new Set(["MERCARI","POSHMARK","DEPOP"]);
function money(n:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n)}
function calc(s:Sale){const cogs=s.lines.reduce((n,l)=>n+((l.cogsAtSale??l.inventoryItem?.cogs??0)*(l.quantity||1)),0);const buyerPaidShipping=BUYER_PAID_SHIPPING.has((s.platform||"").toUpperCase());const hasCogs=s.lines.some(l=>l.cogsAtSale!=null||!!l.inventoryItem);return{revenue:s.saleAmount||0,fees:s.fees||0,shipping:s.shippingCost||0,cogs,profit:(s.saleAmount||0)-(s.fees||0)-(s.shippingCost||0)-cogs,hasCogs,hasFees:(s.fees||0)>0,hasShipping:buyerPaidShipping||(s.shippingCost||0)>0,buyerPaidShipping}}

export default function ProfitPage(){
 const[sales,setSales]=useState<Sale[]>([]),[period,setPeriod]=useState("30");
 useEffect(()=>{fetch('/api/sales').then(r=>r.json()).then(setSales)},[]);
 const filtered=useMemo(()=>{if(period==='ALL')return sales;const days=Number(period),cut=new Date();cut.setDate(cut.getDate()-days);return sales.filter(s=>new Date(s.soldAt)>=cut)},[sales,period]);
 const totals=useMemo(()=>filtered.reduce((a,s)=>{const x=calc(s);a.revenue+=x.revenue;a.fees+=x.fees;a.shipping+=x.shipping;a.cogs+=x.cogs;a.profit+=x.profit;a.cogsCount+=x.hasCogs?1:0;a.feeCount+=x.hasFees?1:0;a.shippingCount+=x.hasShipping?1:0;a.buyerPaidShippingCount+=x.buyerPaidShipping?1:0;return a},{revenue:0,fees:0,shipping:0,cogs:0,profit:0,cogsCount:0,feeCount:0,shippingCount:0,buyerPaidShippingCount:0}),[filtered]);
 const byPlatform=useMemo(()=>{const m:Record<string,{sales:number;revenue:number;fees:number;shipping:number;cogs:number;profit:number;cogsCount:number;feeCount:number;shippingCount:number}>={};for(const s of filtered){const x=calc(s),r=m[s.platform]||(m[s.platform]={sales:0,revenue:0,fees:0,shipping:0,cogs:0,profit:0,cogsCount:0,feeCount:0,shippingCount:0});r.sales++;r.revenue+=x.revenue;r.fees+=x.fees;r.shipping+=x.shipping;r.cogs+=x.cogs;r.profit+=x.profit;r.cogsCount+=x.hasCogs?1:0;r.feeCount+=x.hasFees?1:0;r.shippingCount+=x.hasShipping?1:0}return Object.entries(m).sort((a,b)=>b[1].revenue-a[1].revenue)},[filtered]);
 const avg=filtered.length?totals.profit/filtered.length:0,margin=totals.revenue?totals.profit/totals.revenue*100:0;
 const completeCogs=filtered.length?totals.cogsCount/filtered.length*100:0;
 return <main className="shell"><header className="header"><div><a className="back" href="/">← Dashboard</a><h1>Profit Dashboard</h1><p>Revenue minus the costs RH has actually recorded. Coverage shows what is still missing.</p></div><div className="actions"><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="ALL">All time</option></select></div></header>
 <section className="cards"><div className="card"><span>Revenue</span><strong>{money(totals.revenue)}</strong></div><div className="card"><span>Recorded Profit*</span><strong>{money(totals.profit)}</strong></div><div className="card"><span>Recorded Margin*</span><strong>{margin.toFixed(1)}%</strong></div><div className="card"><span>Avg Recorded Profit*</span><strong>{money(avg)}</strong></div></section>
 <section className="panel"><div className="panelHead"><div><h2>Data Coverage</h2><span>{filtered.length} sale{filtered.length===1?'':'s'} in selected period</span></div></div><div className="health"><div><b>{totals.cogsCount} / {filtered.length}</b><span>Sales with COGS ({completeCogs.toFixed(0)}%)</span></div><div><b>{totals.feeCount} / {filtered.length}</b><span>Sales with fees recorded</span></div><div><b>{totals.shippingCount} / {filtered.length}</b><span>Shipping accounted for ({totals.buyerPaidShippingCount} buyer-paid)</span></div></div></section>
 <section className="panel"><div className="panelHead"><div><h2>Recorded Cost Breakdown</h2><span>Only seller-paid costs currently stored in RH</span></div></div><div className="health"><div><b>{money(totals.fees)}</b><span>Marketplace Fees</span></div><div><b>{money(totals.shipping)}</b><span>Seller-Paid Shipping</span></div><div><b>{money(totals.cogs)}</b><span>COGS</span></div></div></section>
 <section className="panel"><div className="panelHead"><div><h2>Marketplace Performance</h2><span>Recorded profit is provisional until cost coverage is complete</span></div></div><table><thead><tr><th>Marketplace</th><th>Sales</th><th>Revenue</th><th>Recorded Costs</th><th>Recorded Profit*</th><th>COGS Recorded</th></tr></thead><tbody>{byPlatform.map(([p,x])=><tr key={p}><td><b>{p}</b></td><td>{x.sales}</td><td>{money(x.revenue)}</td><td>{money(x.fees+x.shipping+x.cogs)}</td><td><b>{money(x.profit)}</b></td><td>{x.cogsCount}/{x.sales}</td></tr>)}</tbody></table>{!byPlatform.length&&<div className="empty">No sales in this period.</div>}</section>
 <section className="panel"><p className="footnote"><b>* Recorded Profit is not final net profit yet.</b> Historical COGS snapshots are used when available, otherwise RH falls back to the linked inventory item's COGS. Mercari, Poshmark, and Depop shipping is treated as buyer-paid and therefore $0 seller shipping cost. eBay shipping is counted only when an actual seller-paid shipping cost is recorded. Missing fees or COGS can still make recorded profit incomplete.</p></section></main>
}
